on:
  create:
    tags:
      - v*

jobs:
  maven-build:
    uses: ./.github/workflows/maven.yml
  docker-build-publish:
    runs-on: ubuntu-latest
    needs:
      - maven-build
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: tosox-jr:${{ github.ref_name }}
          path: target/tosox-jr.jar
      - name: Login to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/leonbcode/tosox-jr:${{ github.ref_name }}